app/Http/routes.php
	Route::group(['prefix' => 'master'], function()
	{
		//////////////////////////////////////
		// =========ADMINISTRATOR===========//
		//////////////////////////////////////
		Route::resource('administrator', 'MasterAdministratorController', ['except' => 'destroy']);
		Route::group(['prefix' => 'administrator'], function()
		{
			Route::get('{id}/delete', ['as' => 'dashboard.master.administrator.delete', 'uses' => 'MasterAdministratorController@destroy']);	
			/**
			 *  Pivot Kompetensi administrator
			 */
			Route::get('{id}/kompetensi', ['as' => 'dashboard.master.administrator.kompetensi.index','uses' => 'MasterAdministratorController@indexKompetensi']);
			Route::get('{id}/kompetensi/{kompetensi_id}/delete', ['as' => 'dashboard.master.administrator.kompetensi.delete','uses' => 'MasterAdministratorController@deleteKompetensi']);
			Route::get('{id}/kompetensi/create', ['as' => 'dashboard.master.administrator.kompetensi.create','uses' => 'MasterAdministratorController@createKompetensi']);
			Route::post('{id}/kompetensi/store', ['as' => 'dashboard.master.administrator.kompetensi.store','uses' => 'MasterAdministratorController@storeKompetensi']);

			/**
			 *  Pivot Kelompok administrator
			 */
			Route::get('{id}/kelompok', ['as' => 'dashboard.master.administrator.kelompok.index','uses' => 'MasterAdministratorController@indexKelompok']);
			Route::get('{id}/kelompok/{lembagasertifikasi_id}/delete', ['as' => 'dashboard.master.administrator.kelompok.delete','uses' => 'MasterAdministratorController@deleteKelompok']);
			Route::get('{id}/kelompok/create', ['as' => 'dashboard.master.administrator.kelompok.create','uses' => 'MasterAdministratorController@createKelompok']);
			Route::post('{id}/kelompok/store', ['as' => 'dashboard.master.administrator.kelompok.store','uses' => 'MasterAdministratorController@storeKelompok']);
		});

		//////////////////////////////////////
		// =============PESERTA=============//
		//////////////////////////////////////
		Route::resource('peserta', 'MasterPesertaController', ['except' => 'delete']);
		Route::get('peserta/{id}/delete', ['as' => 'dashboard.master.peserta.delete', 'uses' => 'MasterPesertaController@destroy']);

		//////////////////////////////////////
		// ==============ASESOR=============//
		//////////////////////////////////////
		Route::resource('asesor', 'MasterAsesorController', ['except' => 'destroy']);
		Route::group(['prefix' => 'asesor'], function()
		{
			Route::get('{id}/delete', ['as' => 'dashboard.master.asesor.delete', 'uses' => 'MasterAsesorController@destroy']);
			
			Route::group(['prefix' => '{id}/kelompok'], function()
			{
				Route::get('/', ['as' => 'dashboard.master.asesor.kelompok.index','uses' => 'MasterAsesorController@indexkelompok']);
				Route::get('{kelompok_id}/delete', ['as' => 'dashboard.master.asesor.kelompok.delete','uses' => 'MasterAsesorController@deleteKelompok']);
				Route::get('create', ['as' => 'dashboard.master.asesor.kelompok.create','uses' => 'MasterAsesorController@createKelompok']);
				Route::post('store', ['as' => 'dashboard.master.asesor.kelompok.store','uses' => 'MasterAsesorController@storeKelompok']);
			});
			
			Route::get('{id}/testhistory', ['as' => 'dashboard.master.asesor.testhistory.index','uses' => 'MasterAsesorController@indexTest']);

			Route::resource('kompetensiasesor', 'MasterKompetensiasesorController', ['only' => ['create','store']]);
			Route::group(['prefix' => 'kompetensiasesor'], function()
			{	
				Route::get('{asesor_id}', ['as' => 'dashboard.master.kompetensiasesor.asesor.index','uses' => 'MasterKompetensiasesorController@showByAsesor']);
				Route::get('{asesor_id}/create', ['as' => 'dashboard.master.kompetensiasesor.asesor.create','uses' => 'MasterKompetensiasesorController@create']);
				Route::get('detach/{asesor}/{kompetensi}', ['as' => 'dashboard.master.asesor.kompetensiasesor.delete', 'uses' => 'MasterKompetensiasesorController@destroy']);
			});

			// ======================= Route sub bidang asesor ============================ //
			Route::group(['prefix' => '{id}/subbidang'], function()
			{
				Route::get('/', ['as' => 'dashboard.master.asesor.subbidang.index', 'uses' => 'MasterAsesorController@indexSubbidang']);
				Route::get('create', ['as' => 'dashboard.master.asesor.subbidang.create', 'uses' => 'MasterAsesorController@createSubbidang']);
				Route::post('store', ['as' => 'dashboard.master.asesor.subbidang.store', 'uses' => 'MasterAsesorController@storeSubbidang']);
				Route::get('{subbidangId}/delete', ['as' => 'dashboard.master.asesor.subbidang.delete', 'uses' => 'MasterAsesorController@deleteSubbidang']);
			});

			// ========================= Route master Sertifikat Asesor ===================== //
			Route::get('{asesor_id}/sertifikatasesor', ['as' => 'dashboard.master.sertifikatasesor.asesor.index','uses' => 'MasterSertifikatAsesorController@showByAsesor']);
			Route::get('{asesor_id}/sertifikatasesor/create', ['as' => 'dashboard.master.sertifikatasesor.asesor.create','uses' => 'MasterSertifikatAsesorController@create']);
			
			Route::resource('sertifikatasesor', 'MasterSertifikatAsesorController', ['except' => ['destroy','show','index']]);

			Route::group(['prefix' => 'sertifikatasesor'], function()
			{
				Route::get('{id}/delete/{asesor}', ['as' => 'dashboard.master.sertifikatasesor.delete', 'uses' => 'MasterSertifikatAsesorController@destroy']);
				Route::get('{id}/edit', ['as' => 'dashboard.master.sertifikatasesor.edit','uses' => 'MasterSertifikatAsesorController@edit']);
				Route::put('{id}/update/{asesor}', ['as' => 'dashboard.master.sertifikatasesor.update','uses' => 'MasterSertifikatAsesorController@update']);
			});
	
		});

		//////////////////////////////////////
		// ============AKREDITOR============//
		//////////////////////////////////////
		Route::resource('akreditor', 'MasterLembagaController', ['except' => ['destroy','show']]);
		Route::get('akreditor/{id}/delete', ['as' => 'dashboard.master.akreditor.delete', 'uses' => 'MasterLembagaController@destroy']);

		//////////////////////////////////////
		// =======LEMBAGA SERTIFIKASI=======//
		//////////////////////////////////////
		Route::resource('lembagasertifikasi', 'MasterLembagasertifikasiController', ['except' => ['destroy','show']]);
		Route::get('lembagasertifikasi/{id}/delete', ['as' => 'dashboard.master.lembagasertifikasi.delete', 'uses' => 'MasterLembagasertifikasiController@destroy']);

		//////////////////////////////////////
		// ==============BIDANG=============//
		//////////////////////////////////////
		Route::resource('bidang', 'MasterBidangController', ['except' => ['destroy','show']]);
		Route::group(['prefix' => 'bidang'], function()
		{
			Route::get('{id}/delete', ['as' => 'dashboard.master.bidang.delete', 'uses' => 'MasterBidangController@destroy']);

			// =========================== sub bidang section ======================= //
			Route::get('{bidang_id}/subbidang', ['as' => 'dashboard.master.subbidang.bidang.index','uses' => 'MasterSubbidangController@showByBidang']);
			Route::get('{bidang_id}/subbidang/create', ['as' => 'dashboard.master.subbidang.bidang.create','uses' => 'MasterSubbidangController@create']);

			Route::group(['prefix' => 'subbidang'], function()
			{
				Route::get('create', ['as' => 'dashboard.master.subbidang.create','uses' => 'MasterSubbidangController@create']);
				Route::post('store', ['as' => 'dashboard.master.subbidang.store','uses' => 'MasterSubbidangController@store']);

				Route::get('{id}/edit', ['as' => 'dashboard.master.subbidang.edit','uses' => 'MasterSubbidangController@edit']);
				Route::put('{id}/update', ['as' => 'dashboard.master.subbidang.update','uses' => 'MasterSubbidangController@update']);
				Route::get('{id}/delete', ['as' => 'dashboard.master.subbidang.delete', 'uses' => 'MasterSubbidangController@destroy']);
			});
			
		});

		//////////////////////////////////////
		// =========UNIT KOMPETENSI=========//
		//////////////////////////////////////
		Route::resource('kompetensi', 'MasterKompetensiController', ['except' => ['destroy','show']]);

		Route::group(['prefix' => 'kompetensi'], function()
		{
			Route::get('{id}/delete', ['as' => 'dashboard.master.kompetensi.delete', 'uses' => 'MasterKompetensiController@destroy']);

			// ============================== Route master elemen kompetensi ================== //
			Route::resource('elemenkompetensi', 'MasterElemenkompetensiController', ['except' => ['destroy','show','index']]);
			
			Route::group(['prefix' => '{kompetensi_id}/elemenkompetensi'], function()
			{
				Route::get('/', ['as' => 'dashboard.master.elemenkompetensi.kompetensi.index','uses' => 'MasterElemenkompetensiController@showByKompetensi']);
				Route::get('create', ['as' => 'dashboard.master.elemenkompetensi.kompetensi.create','uses' => 'MasterElemenkompetensiController@create']);
			});
			
			Route::get('elemenkompetensi/{id}/delete', ['as' => 'dashboard.master.elemenkompetensi.delete', 'uses' => 'MasterElemenkompetensiController@destroy']);
		});

		//////////////////////////////////////
		// ===============UNIT==============//
		//////////////////////////////////////
		Route::group(['prefix'=>'unit'], function()
		{
			Route::get('/', ['as'=>'dashboard.master.unit.index', 'uses' => 'MasterUnitsController@index']);
			
			Route::resource('diklat', 'MasterUdiklatController', ['except' => 'show','destroy']);
			Route::get('diklat/{id}/delete', ['as' => 'dashboard.master.unit.diklat.delete', 'uses' => 'MasterUdiklatController@destroy']);
			Route::get('diklat/api/induk/{id}', ['dashboard.master.unit.diklat.api.induk', 'uses' => 'MasterUdiklatController@getUnitInduk']);
			
			Route::resource('induk', 'MasterUindukController', ['except' => 'show','destroy']);
			Route::get('induk/{id}/delete', ['as' => 'dashboard.master.unit.induk.delete', 'uses' => 'MasterUindukController@destroy']);

app/Http/Controllers/MasterKompetensiController.php
<?php namespace Certification\Http\Controllers;

use Certification\Http\Requests\StoreMasterKompetensiRequest;
use Certification\Http\Controllers\Controller;
use Certification\Repositories\Kompetensi\InterfaceKompetensiRepository;
use Certification\Repositories\Bidang\InterfaceSubbidangRepository;

use Illuminate\Http\Request as Request;
use \Config, \Flash;

class MasterKompetensiController extends Controller {

	/**
	 * Kompetensi Repository
	 * @var interface
	 * 
	 */
	private $kompetensiRepository;
	
	/**
	 * Module title
	 * 
	 * @var String
	 */
	private $title;

	/**
	 * Class instance
	 * 
	 * @param InterfaceKompetensiRepository $kompetensiRepository kompetensi Repository
	 */
	public function __construct(InterfaceKompetensiRepository $kompetensiRepository)
	{
		$this->kompetensiRepository = $kompetensiRepository;
		$this->title                = 'Manajemen Kompetensi';
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @param Request $request Http request
	 * @return Response
	 */
	public function index(Request $request)
	{
		$data['title']             = $this->title;
		$data['subtitle']          = 'Daftar master kompetensi';
		$data['kompetensi']        = $this->kompetensiRepository->all('paginate');
		$data['pagination_number'] = numbering_pagination($request, Config::get('certification.default_pagination_count'));
		
		return view('backend.masterkompetensi.index', compact('data'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @param InterfaceSubbidangRepository $subbidang Subbidang repository
	 * @return Response
	 */
	public function create(InterfaceSubbidangRepository $subbidang)
	{
		$data['title']     = $this->title;
		$data['subtitle']  = "Tambah data master kompetensi";
		$data['subbidang'] = $subbidang->lists();
		return view('backend.masterkompetensi.create', compact('data'));
	}

	/**
	 * Store a newly created resource in storage.
	 * 
	 * @param StoreMasterKompetensi $request Filter and request validator
	 * @return Response
	 */
	public function store(StoreMasterKompetensiRequest $request)
	{
		$affected = $this->kompetensiRepository->store($request->except('_token'));
		if ($affected) {
			Flash::success('Data kompetensi berhasil disimpan');
			return redirect()->route('dashboard.master.kompetensi.index');
		}
		Flash::error('Data kompetensi gagal disimpan');
		return redirect()->route('dashboard.master.kompetensi.create');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param InterfaceSubbidangRepository $subbidang Subbidang repository
	 * @param  int  $id
	 * @return Response
	 */
	public function edit(InterfaceSubbidangRepository $subbidang, $id)
	{
		$data['title']      = $this->title;
		$data['subtitle']   = "Edit data master kompetensi";
		$data['subbidang']  = $subbidang->lists();
		$data['kompetensi'] = $this->kompetensiRepository->getById($id);
		return view('backend.masterkompetensi.edit', compact('data'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(StoreMasterKompetensiRequest $request, $id)
	{
		$affected = $this->kompetensiRepository->update($id, $request->except('_token','_method'));
		if ($affected) {
			Flash::success('Data kompetensi berhasil diperbarui');
			return redirect()->route('dashboard.master.kompetensi.index');
		}
		Flash::error('Data kompetensi gagal diperbarui');
		return redirect()->route('dashboard.master.kompetensi.edit',['id'=>$id]);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$this->kompetensiRepository->delete($id);
		Flash::success('Data kompetensi berhasil dihapus');
		return redirect()->route('dashboard.master.kompetensi.index');
	}

	/**
	 * Get array list of kompetensi resource by subbidang
	 * 
	 * @param  Integer $id Subbidang id
	 * @return JSON
	 */
	public function apiGetBySubbidang($id)
	{
		return $this->kompetensiRepository->getBySubbidang($id);
	}

	/**
	 * [apiGetBelongsToBidang description]
	 * 
	 * @param  [type] $id [description]
	 * @return [type]     [description]
	 */
	public function apiGetBelongsToBidang($id)
	{
		return $this->kompetensiRepository->getBidangs($id);
	}

}

resources/views/backend/masterkompetensi/create.blade.php
@extends('layouts.backend.master')
@section('content')
<div class="row">
	<div class="col-md-8">
		<div class="box box-primary">
			<div class="box-header with-border">
		     <h3>Form Tambah Kompetensi</h3>
		    </div><!-- /.box-header -->
		    <div class="box-body">
		    	@if (Session::has('flash_notification.message'))
				    <div class="alert alert-{{ Session::get('flash_notification.level') }}">
				        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				        {{ Session::get('flash_notification.message') }}
				    </div>
				@endif
		    	<form class="form-horizontal" action="{{ route('dashboard.master.kompetensi.store') }}" method="post">
		    		<input type="hidden" name="_token" value="{{ csrf_token() }}">
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Subbidang</label>
                      <div class="col-sm-7">
	              		{!! Form::select('subbidang_id', $data['subbidang'], null,['class'=>'form-control']) !!} 
                      </div>
		    		</div>
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Nama Kompetensi</label>
                      <div class="col-sm-7">
                          <input type="text" class="form-control" placeholder="Nama Kompetensi" name="nama_kompetensi" required>
                      </div>
		    		</div>
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Nama Kompetensi (English)</label>
                      <div class="col-sm-7">
                          <input type="text" class="form-control" placeholder="Nama Kompetensi (English)" name="nama_kompetensi_english">
                      </div>
		    		</div>
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Kode DJK</label>
                      <div class="col-sm-7">
                          <input type="text" class="form-control" placeholder="Kode DJK" name="kodedjk">
                      </div>
		    		</div>
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Kode SKKNI</label>
                      <div class="col-sm-7">
                          <input type="text" class="form-control" placeholder="Kode SKKNI" name="kodeskkni">
                      </div>
		    		</div>
		    </div>
		    <div class="box-footer">
		    	<div class="col-sm-4 col-md-offset-3">
    				<button type="submit" class="btn btn-primary">Simpan</button>&nbsp;
		            <a href="{{ route('dashboard.master.kompetensi.index') }}" class="btn btn-warning">Kembali</a>
    			</div>
		    </div>
		    </form>
		</div>
	</div>
</div>		    
@stop		    

resources/views/backend/masterkompetensi/edit.blade.php
@extends('layouts.backend.master')
@section('content')
<div class="row">
	<div class="col-md-8">
		<div class="box box-primary">
			<div class="box-header with-border">
		     <h3>Form Edit Kompetensi</h3>
		    </div><!-- /.box-header -->
		    <div class="box-body">
		    	@if (Session::has('flash_notification.message'))
				    <div class="alert alert-{{ Session::get('flash_notification.level') }}">
				        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				        {{ Session::get('flash_notification.message') }}
				    </div>
				@endif
		    	<form class="form-horizontal" action="{{ route('dashboard.master.kompetensi.update', ['id' => $data['kompetensi']->id]) }}" method="post">
		    		<input type="hidden" name="_token" value="{{ csrf_token() }}">
		    		<input type="hidden" name="_method" value="put">
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Subbidang</label>
                      <div class="col-sm-7">
	              		{!! Form::select('subbidang_id', $data['subbidang'], $data['kompetensi']->subbidang_id,['class'=>'form-control']) !!} 
                      </div>
		    		</div>
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Nama Kompetensi</label>
                      <div class="col-sm-7">
                          <input type="text" class="form-control" placeholder="Nama Kompetensi" name="nama_kompetensi" value="{{ $data['kompetensi']->nama_kompetensi }}" required>
                      </div>
		    		</div>
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Nama Kompetensi (English)</label>
                      <div class="col-sm-7">
                          <input type="text" class="form-control" placeholder="Nama Kompetensi (English)" name="nama_kompetensi_english" value="{{ $data['kompetensi']->nama_kompetensi_english }}">
                      </div>
		    		</div>
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Kode DJK</label>
                      <div class="col-sm-7">
                          <input type="text" class="form-control" placeholder="Kode DJK" name="kodedjk" value="{{ $data['kompetensi']->kodedjk }}">
                      </div>
		    		</div>
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Kode SKKNI</label>
                      <div class="col-sm-7">
                          <input type="text" class="form-control" placeholder="Kode SKKNI" name="kodeskkni" value="{{ $data['kompetensi']->kodeskkni }}">
                      </div>
		    		</div>
		    </div>
		    <div class="box-footer">
		    	<div class="col-sm-4 col-md-offset-3">
    				<button type="submit" class="btn btn-primary">Update</button>&nbsp;
		            <a href="{{ route('dashboard.master.kompetensi.index') }}" class="btn btn-warning">Kembali</a>
    			</div>
		    </div>
		    </form>
		</div>
	</div>
</div>		    
@stop		    

resources/views/backend/masterkompetensi/index.blade.php
@extends('layouts.backend.master')
@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="box box-primary">
		@if(Auth::user()->can('can_write_masterkompetensi'))
			<div class="box-header with-border">
		      <a href="{{ route('dashboard.master.kompetensi.create') }}" class="btn btn-sm btn-success"><i class="fa fa-plus"></i> Tambah Kompetensi</a>&nbsp; 
		      <a href="{{ route('dashboard.master.kompetensi.elemenkompetensi.create') }}" class="btn btn-sm btn-info"><i class="fa fa-plus"></i> Tambah Elemen Kompetensi</a>
		    </div><!-- /.box-header -->
		@endif
		    <div class="box-body">
		    @if (Session::has('flash_notification.message'))
			    <div class="alert alert-{{ Session::get('flash_notification.level') }}">
			        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			        {{ Session::get('flash_notification.message') }}
			    </div>
			@endif
		    	 <div class="table-responsive">
			        <table class="table no-margin table-condensed table-bordered table-hover">
			          <thead class="bg-info">
				          <tr>
				          	<th>No.</th>
				          	<th class="col-md-4">Nama Kompetensi</th>
				          	<th class="col-md-1">Kode DJK</th>
				          	<th class="col-md-1">Kode SKKNI</th>
				          	<th>Elemen Kompetensi</th>
				          	<th>Sub Bidang</th>
				          	<th class="col-md-2 text-center">Aksi</th>
				          </tr>
			          </thead>
			          <tbody>
			          @foreach($data['kompetensi'] as $kompetensi)
				          <tr>
				          	<td>{{ $data['pagination_number'] }}</td>
				          	<td>{{ $kompetensi->nama_kompetensi }} {!! (! empty($kompetensi->nama_kompetensi_english)) ? '(<em>'.$kompetensi->nama_kompetensi_english.'</em>)' : '' !!}</td>
				          	<td>{{ $kompetensi->kodedjk }}</td>
				          	<td>{{ $kompetensi->kodeskkni }}</td>
				          	<td><a href="{{ route('dashboard.master.elemenkompetensi.kompetensi.index',['kompetensi_id' => $kompetensi->id]) }}">{{ $kompetensi->elemenKompetensi->count() }} Elemen</a></td>
				          	<td>{{ $kompetensi->subbidang->nama_subbidang }}</td>
				          	<td class="text-center">
				          	@if(Auth::user()->can('can_write_masterkompetensi'))
				          		<a href="{{ route('dashboard.master.kompetensi.edit', ['id' => $kompetensi->id]) }}" class="btn btn-sm btn-warning"><i class="fa fa-edit"></i> Edit</a>
				          		<a href="{{ route('dashboard.master.kompetensi.delete', ['id' => $kompetensi->id]) }}" class="btn btn-sm btn-danger" onclick="return confirm('Hapus data?'); "><i class="fa fa-trash"></i> Delete</a>
				          	@else
				          		-
				          	@endif
				          	</td>
				          </tr>
				      <?php $data['pagination_number']++; ?>    
			          @endforeach
			          </tbody>
			        </table><br>
			        <div class="text-center">
			        	{!! paginationHelper($data['kompetensi']->render()) !!}
			        </div>
			    </div>      
		    </div>
		</div>
	</div>
</div>
@stop