app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'UserAuthController@index');
Route::get('register', ['as' => 'register.index', 'uses' => 'Registration\RegistrationController@register']);
Route::post('register', ['as' => 'register.post', 'uses' => 'Registration\RegistrationController@storeRegister']);

Route::get('signin', ['as' => 'user.signin.index', 'uses' => 'UserAuthController@index']);
Route::post('signin', ['as' => 'user.signin.post', 'uses' => 'UserAuthController@signingin']);
Route::get('signout', ['as' => 'user.signout', 'uses' => 'UserAuthController@signingout']);

Route::group(['prefix' => 'dashboard','middleware' => 'auth'], function()
{
	Route::get('', ['as' => 'dashboard.index', 'uses' => 'DashboardController@index']);
	
	// ==================== Password management routes section ======================== //
	Route::group(['prefix' => 'password'], function()
	{
		Route::get('change', ['as' => 'dashboard.password.change', 'uses' => 'UserAuthController@changePassword']);
		Route::put('update', ['as' => 'dashboard.password.update', 'uses' => 'UserAuthController@updatePassword']);
	});


/////////////////////////////////////////////////////////////////////////////////////////////
// =================================== MASTER ROUTES ===================================== //
/////////////////////////////////////////////////////////////////////////////////////////////

	Route::group(['prefix' => 'master'], function()
	{
		//////////////////////////////////////
		// =========ADMINISTRATOR===========//
		//////////////////////////////////////
		Route::resource('administrator', 'MasterAdministratorController', ['except' => 'destroy']);
		Route::group(['prefix' => 'administrator'], function()
		{
			Route::get('{id}/delete', ['as' => 'dashboard.master.administrator.delete', 'uses' => 'MasterAdministratorController@destroy']);	
			/**
			 *  Pivot Kompetensi administrator
			 */
			Route::get('{id}/kompetensi', ['as' => 'dashboard.master.administrator.kompetensi.index','uses' => 'MasterAdministratorController@indexKompetensi']);
			Route::get('{id}/kompetensi/{kompetensi_id}/delete', ['as' => 'dashboard.master.administrator.kompetensi.delete','uses' => 'MasterAdministratorController@deleteKompetensi']);
			Route::get('{id}/kompetensi/create', ['as' => 'dashboard.master.administrator.kompetensi.create','uses' => 'MasterAdministratorController@createKompetensi']);
			Route::post('{id}/kompetensi/store', ['as' => 'dashboard.master.administrator.kompetensi.store','uses' => 'MasterAdministratorController@storeKompetensi']);

			/**
			 *  Pivot Kelompok administrator
			 */
			Route::get('{id}/kelompok', ['as' => 'dashboard.master.administrator.kelompok.index','uses' => 'MasterAdministratorController@indexKelompok']);
			Route::get('{id}/kelompok/{lembagasertifikasi_id}/delete', ['as' => 'dashboard.master.administrator.kelompok.delete','uses' => 'MasterAdministratorController@deleteKelompok']);
			Route::get('{id}/kelompok/create', ['as' => 'dashboard.master.administrator.kelompok.create','uses' => 'MasterAdministratorController@createKelompok']);
			Route::post('{id}/kelompok/store', ['as' => 'dashboard.master.administrator.kelompok.store','uses' => 'MasterAdministratorController@storeKelompok']);
		});

		//////////////////////////////////////
		// =============PESERTA=============//
		//////////////////////////////////////
		Route::resource('peserta', 'MasterPesertaController', ['except' => 'delete']);
		Route::get('peserta/{id}/delete', ['as' => 'dashboard.master.peserta.delete', 'uses' => 'MasterPesertaController@destroy']);

		//////////////////////////////////////
		// ==============ASESOR=============//
		//////////////////////////////////////
		Route::resource('asesor', 'MasterAsesorController', ['except' => 'destroy']);
		Route::group(['prefix' => 'asesor'], function()
		{
			Route::get('{id}/delete', ['as' => 'dashboard.master.asesor.delete', 'uses' => 'MasterAsesorController@destroy']);
			
			Route::group(['prefix' => '{id}/kelompok'], function()
			{
				Route::get('/', ['as' => 'dashboard.master.asesor.kelompok.index','uses' => 'MasterAsesorController@indexkelompok']);
				Route::get('{kelompok_id}/delete', ['as' => 'dashboard.master.asesor.kelompok.delete','uses' => 'MasterAsesorController@deleteKelompok']);
				Route::get('create', ['as' => 'dashboard.master.asesor.kelompok.create','uses' => 'MasterAsesorController@createKelompok']);
				Route::post('store', ['as' => 'dashboard.master.asesor.kelompok.store','uses' => 'MasterAsesorController@storeKelompok']);
			});
			
			Route::get('{id}/testhistory', ['as' => 'dashboard.master.asesor.testhistory.index','uses' => 'MasterAsesorController@indexTest']);

			Route::resource('kompetensiasesor', 'MasterKompetensiasesorController', ['only' => ['create','store']]);
			Route::group(['prefix' => 'kompetensiasesor'], function()
			{	
				Route::get('{asesor_id}', ['as' => 'dashboard.master.kompetensiasesor.asesor.index','uses' => 'MasterKompetensiasesorController@showByAsesor']);
				Route::get('{asesor_id}/create', ['as' => 'dashboard.master.kompetensiasesor.asesor.create','uses' => 'MasterKompetensiasesorController@create']);
				Route::get('detach/{asesor}/{kompetensi}', ['as' => 'dashboard.master.asesor.kompetensiasesor.delete', 'uses' => 'MasterKompetensiasesorController@destroy']);
			});

			// ======================= Route sub bidang asesor ============================ //
			Route::group(['prefix' => '{id}/subbidang'], function()
			{
				Route::get('/', ['as' => 'dashboard.master.asesor.subbidang.index', 'uses' => 'MasterAsesorController@indexSubbidang']);
				Route::get('create', ['as' => 'dashboard.master.asesor.subbidang.create', 'uses' => 'MasterAsesorController@createSubbidang']);
				Route::post('store', ['as' => 'dashboard.master.asesor.subbidang.store', 'uses' => 'MasterAsesorController@storeSubbidang']);
				Route::get('{subbidangId}/delete', ['as' => 'dashboard.master.asesor.subbidang.delete', 'uses' => 'MasterAsesorController@deleteSubbidang']);
			});

			// ========================= Route master Sertifikat Asesor ===================== //
			Route::get('{asesor_id}/sertifikatasesor', ['as' => 'dashboard.master.sertifikatasesor.asesor.index','uses' => 'MasterSertifikatAsesorController@showByAsesor']);
			Route::get('{asesor_id}/sertifikatasesor/create', ['as' => 'dashboard.master.sertifikatasesor.asesor.create','uses' => 'MasterSertifikatAsesorController@create']);
			
			Route::resource('sertifikatasesor', 'MasterSertifikatAsesorController', ['except' => ['destroy','show','index']]);

			Route::group(['prefix' => 'sertifikatasesor'], function()
			{
				Route::get('{id}/delete/{asesor}', ['as' => 'dashboard.master.sertifikatasesor.delete', 'uses' => 'MasterSertifikatAsesorController@destroy']);
				Route::get('{id}/edit', ['as' => 'dashboard.master.sertifikatasesor.edit','uses' => 'MasterSertifikatAsesorController@edit']);
				Route::put('{id}/update/{asesor}', ['as' => 'dashboard.master.sertifikatasesor.update','uses' => 'MasterSertifikatAsesorController@update']);
			});
	
		});

		//////////////////////////////////////
		// ============AKREDITOR============//
		//////////////////////////////////////
		Route::resource('akreditor', 'MasterLembagaController', ['except' => ['destroy','show']]);
		Route::get('akreditor/{id}/delete', ['as' => 'dashboard.master.akreditor.delete', 'uses' => 'MasterLembagaController@destroy']);

		//////////////////////////////////////
		// =======LEMBAGA SERTIFIKASI=======//
		//////////////////////////////////////
		Route::resource('lembagasertifikasi', 'MasterLembagasertifikasiController', ['except' => ['destroy','show']]);
		Route::get('lembagasertifikasi/{id}/delete', ['as' => 'dashboard.master.lembagasertifikasi.delete', 'uses' => 'MasterLembagasertifikasiController@destroy']);

		//////////////////////////////////////
		// ==============BIDANG=============//
		//////////////////////////////////////
		Route::resource('bidang', 'MasterBidangController', ['except' => ['destroy','show']]);
		Route::group(['prefix' => 'bidang'], function()
		{
			Route::get('{id}/delete', ['as' => 'dashboard.master.bidang.delete', 'uses' => 'MasterBidangController@destroy']);

			// =========================== sub bidang section ======================= //
			Route::get('{bidang_id}/subbidang', ['as' => 'dashboard.master.subbidang.bidang.index','uses' => 'MasterSubbidangController@showByBidang']);
			Route::get('{bidang_id}/subbidang/create', ['as' => 'dashboard.master.subbidang.bidang.create','uses' => 'MasterSubbidangController@create']);

			Route::group(['prefix' => 'subbidang'], function()
			{
				Route::get('create', ['as' => 'dashboard.master.subbidang.create','uses' => 'MasterSubbidangController@create']);
				Route::post('store', ['as' => 'dashboard.master.subbidang.store','uses' => 'MasterSubbidangController@store']);

				Route::get('{id}/edit', ['as' => 'dashboard.master.subbidang.edit','uses' => 'MasterSubbidangController@edit']);
				Route::put('{id}/update', ['as' => 'dashboard.master.subbidang.update','uses' => 'MasterSubbidangController@update']);
				Route::get('{id}/delete', ['as' => 'dashboard.master.subbidang.delete', 'uses' => 'MasterSubbidangController@destroy']);
			});
			
		});

		//////////////////////////////////////
		// =========UNIT KOMPETENSI=========//
		//////////////////////////////////////
		Route::resource('kompetensi', 'MasterKompetensiController', ['except' => ['destroy','show']]);

		Route::group(['prefix' => 'kompetensi'], function()
		{

resources/views/layouts/backend/header.blade.php
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <a href="{{ route('dashboard.index') }}" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>PLN</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><img src="{{ url().'/assets/dist/img/logo-pln-corpu.png'}}" style="width: 60%; height: 60% "></span>
  </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
      
        <!-- User Account Menu -->
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs">{{ Auth::user()->nip }}</span>
          </a>
          <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
              <p>
                {{ Auth::user()->nip }} - {{ (Auth::user()->roles->count() > 0) ? Auth::user()->roles[0]->display_name : '-' }}
              </p>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="{{ route('dashboard.password.change') }}" class="btn btn-default btn-flat">Ganti Password</a>
              </div>
              <div class="pull-right">
                <a href="{{ route('user.signout') }}" class="btn btn-default btn-flat">Sign out</a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

resources/views/layouts/backend/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header">MENU UTAMA</li>
      <!-- Optionally, you can add icons to the links -->
@if(Auth::user()->can('can_read_maindashboard'))
      <li class="{{ checkActiveMenu('dashboard') }}"><a href="{{ url('dashboard') }}"><i class='fa fa-dashboard'></i> <span>Home</span></a></li>
@endif

<!--////////////////////////////////////////////////////-->
<!--////////////////////////MASTER//////////////////////-->
<!--////////////////////////////////////////////////////-->
@if(isTreeMenuAccessible('master'))
      <li class="treeview {{ checkActiveMenu('dashboard/master/*') }}">
        <a href="#"><i class='fa fa-database'></i> <span>Data Master</span><i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">

<!--//////////////////////////-->
<!--///////ADMINISTRATOR//////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_masteradministrator'))

          <li class="{{ checkActiveMenu('dashboard/master/administrator*') }}"><a href="{{ route('dashboard.master.administrator.index') }}"><i class='fa fa-user'></i> <span>Administrator</span></a></li>
@endif

<!--//////////////////////////-->
<!--//////////PESERTA/////////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_masterpeserta'))   

          <li class="{{ checkActiveMenu('dashboard/master/peserta*') }}"><a href="{{ route('dashboard.master.peserta.index') }}"><i class='fa fa-user-plus'></i> <span>Peserta</span></a></li>
@endif

<!--//////////////////////////-->
<!--//////////ASESOR//////////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_masterasesor'))
  
          <li class="{{ checkActiveMenu('dashboard/master/asesor*') }}"><a href="{{ route('dashboard.master.asesor.index') }}"><i class='fa fa-group'></i> <span>Asesor</span></a></li>
@endif

<!--//////////////////////////-->
<!--/////////AKREDITOR////////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_masterakreditor'))

          <li class="{{ checkActiveMenu('dashboard/master/akreditor*') }}"><a href="{{ route('dashboard.master.akreditor.index') }}"><i class='fa fa-building'></i> <span>Akreditor</span></a></li>
@endif

<!--//////////////////////////-->
<!--////LEMBAGA SERTIFIKASI///-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_masterlembagasertifikasi'))

          <li class="{{ checkActiveMenu('dashboard/master/lembagasertifikasi*') }}"><a href="{{ route('dashboard.master.lembagasertifikasi.index') }}"><i class='fa fa-building'></i> <span>Lembaga Sertifikasi</span></a></li>
@endif

<!--//////////////////////////-->
<!--//////////BIDANG//////////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_masterbidang'))

          <li class="{{ checkActiveMenu('dashboard/master/bidang*') }}"><a href="{{ route('dashboard.master.bidang.index') }}"><i class='fa fa-crosshairs'></i> <span>Bidang</span></a></li>
@endif

<!--//////////////////////////-->
<!--/////////KOMPETENSI///////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_masterkompetensi'))

          <li class="{{ checkActiveMenu('dashboard/master/kompetensi*') }}"><a href="{{ route('dashboard.master.kompetensi.index') }}"><i class='fa fa-crosshairs'></i> <span>Unit Kompetensi</span></a></li>
@endif

<!--//////////////////////////-->
<!--////////////UNIT//////////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_masterunit'))

          <li class="{{ checkActiveMenu('dashboard/master/unit*') }}"><a href="{{ route('dashboard.master.unit.index') }}"><i class='fa fa-external-link'></i> <span>Unit</span></a></li>
@endif

<!--//////////////////////////-->
<!--//////////JABATAN/////////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_masterjenjangjabatan'))

          <li class="{{ checkActiveMenu('dashboard/master/jenjang*') }}"><a href="{{ route('dashboard.master.jenjang.index') }}"><i class='fa fa-briefcase'></i> <span>Jenjang Jabatan</span></a></li>
@endif

<!--//////////////////////////-->
<!--////////PENDIDIKAN////////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_masterpendidikan'))

          <li class="{{ checkActiveMenu('dashboard/master/pendidikan*') }}"><a href="{{ route('dashboard.master.pendidikan.index') }}"><i class='fa fa-institution'></i> <span>Pendidikan</span></a></li>
@endif

<!--//////////////////////////-->
<!--//////////GRADE///////////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_mastergrade'))

          <li class="{{ checkActiveMenu('dashboard/master/grade*') }}"><a href="{{ route('dashboard.master.grade.index') }}"><i class='fa fa-graduation-cap'></i> <span>Jenjang Grade</span></a></li>
@endif

<!--//////////////////////////-->
<!--///////////BIAYA//////////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_masterkomponenbiaya'))
          <li class="{{ checkActiveMenu('dashboard/master/komponenbiaya*') }}"><a href="{{ route('dashboard.master.komponenbiaya.index') }}"><i class='fa fa-money'></i> <span>Komponen Biaya</span></a></li>
@endif

<!--//////////////////////////-->
<!--////////////ROLE//////////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_masterrole'))

          <li class="{{ checkActiveMenu('dashboard/master/userrole*') }}"><a href="{{ route('dashboard.master.userrole.index') }}"><i class="fa fa-users"></i> Role</a></li>
@endif
        </ul>
      </li>
@endif
{{-- end of tree data master --}}

<!--////////////////////////////////////////////////////-->
<!--///////////////////////REGISTRASI///////////////////-->
<!--////////////////////////////////////////////////////-->
@if(Auth::user()->hasRole('superadmin') )
<li class="{{ checkActiveMenu('dashboard/registration*') }}"><a href="{{ route('dashboard.registration.index') }}"><i class='fa fa-plus'></i> <span>Registrasi</span></a></li>
@endif

<!--////////////////////////////////////////////////////-->
<!--//////////////////////PERMOHONAN////////////////////-->
<!--////////////////////////////////////////////////////-->
@if(isTreeMenuAccessible('permohonan'))
      <li class="treeview {{ checkActiveMenu('dashboard/permohonan/*') }}">
        <a href="#"><i class='fa fa-edit'></i> <span>Permohonan</span><i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
@if(Auth::user()->can('can_read_permohonan'))
           <li class="{{ checkActiveMenu('dashboard/permohonan*') }}"><a href="{{ route('dashboard.permohonan.index') }}"><i class='fa fa-edit'></i> <span>Permohonan Surat</span></a></li>
@endif

@if(Auth::user()->can('can_read_permohonan'))
           <li class="{{ checkActiveMenu('dashboard/permohonansdm*') }}"><a href="{{ route('dashboard.permohonansdm.index') }}"><i class='fa fa-edit'></i> <span>Permohonan SDM</span></a></li>           
@endif
        </ul>
      </li>  
@endif
{{-- end of tree permohonan --}}

<!--////////////////////////////////////////////////////-->
<!--////////////////////////EVALUASI////////////////////-->
<!--////////////////////////////////////////////////////-->
@if(Auth::user()->can('can_read_evaluasi'))
      <li class="{{ checkActiveMenu('dashboard/evaluasi*') }}"><a href="{{ route('dashboard.evaluasi.index') }}"><i class='fa fa-check-square-o'></i> <span>Evaluasi</span></a></li>
@endif

<!--////////////////////////////////////////////////////-->
<!--//////////////////////PENJADWALAN///////////////////-->
<!--////////////////////////////////////////////////////-->
@if(Auth::user()->can('can_read_penjadwalan'))
      <li class="{{ checkActiveMenu('dashboard/penjadwalan*') }}"><a href="{{ route('dashboard.penjadwalan.index') }}"><i class='fa fa-clock-o'></i> <span>Penjadwalan</span></a></li>
@endif

<!--////////////////////////////////////////////////////-->
<!--//////////////////////PELAKSANAAN///////////////////-->
<!--////////////////////////////////////////////////////-->
@if(Auth::user()->can('can_read_pelaksanaan'))
      <li class="{{ checkActiveMenu('dashboard/pelaksanaan*') }}"><a href="{{ route('dashboard.pelaksanaan.index') }}"><i class='fa fa-pencil-square-o'></i> <span>Pelaksanaan</span></a></li>
@endif

<!--////////////////////////////////////////////////////-->
<!--///////////////////////SERTIFIKAT///////////////////-->
<!--////////////////////////////////////////////////////-->
@if(isTreeMenuAccessible('sertifikat'))
      <li class="treeview {{ checkActiveMenu('dashboard/sertifikat/*') }}">
        <a href="#"><i class='fa fa-certificate'></i> <span>Sertifikat</span><i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
<!--//////////////////////////-->
<!--//////////SER BARU////////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_sertifikatbaru'))
           <li class="{{ checkActiveMenu('dashboard/sertifikat/baru*') }}"><a href="{{ route('dashboard.sertifikat.baru.index') }}"><i class='fa fa-certificate'></i> <span>Sertifikat Baru</span></a></li>
@endif

<!--//////////////////////////-->
<!--////SERT PERPANJANGAN/////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_sertifikatperpanjangan'))
           <li class="{{ checkActiveMenu('dashboard/sertifikat/perpanjangan*') }}"><a href="{{ route('dashboard.sertifikat.perpanjangan.index') }}"><i class='fa fa-certificate'></i> <span>Sertifikat Perpanjangan</span></a></li>
@endif

        </ul>
      </li>  
@endif
{{-- end of tree sertifikat --}}

<!--////////////////////////////////////////////////////-->
<!--////////////////////////LAPORAN/////////////////////-->
<!--////////////////////////////////////////////////////-->
@if(isTreeMenuAccessible('report'))
      <li class="treeview {{ checkActiveMenu('dashboard/report/*') }}">
        <a href="#"><i class='fa fa-stack-overflow'></i> <span>Laporan</span><i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">

<!--//////////////////////////-->
<!--/////////PELAKSANAAN//////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_laporanpelaksanaan'))
          <li class="{{ checkActiveMenu('dashboard/report/pelaksanaan*') }}"><a href="{{ route('report.pelaksanaan.index') }}"><i class='fa fa-bar-chart'></i> <span>Hasil Pelaksanaan</span></a></li>
@endif

<!--//////////////////////////-->
<!--/////////EVALUASI/////////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_laporanevaluasi'))
          <li class="{{ checkActiveMenu('dashboard/report/evaluasi*') }}"><a href="{{ route('report.evaluasi.index') }}"><i class='fa fa-bar-chart'></i> <span>Hasil Evaluasi</span></a></li>
@endif

<!--//////////////////////////-->
<!--//////////ASESOR//////////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_laporanasesor'))
          <li class="{{ checkActiveMenu('dashboard/report/asesor*') }}"><a href="{{ route('report.asesor.index') }}"><i class='fa fa-bar-chart'></i> <span>Assesor</span></a></li>
@endif

<!--//////////////////////////-->
<!--////////KOMPETENSI////////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_laporansebarankompetensi'))
          <li class="{{ checkActiveMenu('dashboard/report/sebarankompetensi*') }}"><a href="{{ route('report.sebarankompetensi.index') }}"><i class='fa fa-bar-chart'></i> <span>Sebaran Kompetensi</span></a></li>
@endif

<!--//////////////////////////-->
<!--/////////KELULUSAN////////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_laporanhasilkelulusan'))
          <li class="{{ checkActiveMenu('dashboard/report/kelulusan*') }}"><a href="{{ route('report.kelulusan.index') }}"><i class='fa fa-bar-chart'></i> <span>Hasil Kelulusan</span></a></li>
@endif

<!--//////////////////////////-->
<!--///////////BIAYA//////////-->
<!--//////////////////////////-->
@if(Auth::user()->can('can_read_laporanbiaya'))
          <li class="{{ checkActiveMenu('dashboard/report/biaya*') }}"><a href="{{ route('report.biaya.index') }}"><i class='fa fa-bar-chart'></i> <span>Biaya</span></a></li> 
@endif
        </ul>
      </li>
@endif
{{-- end of tree report --}}
     
      <li><a href="{{ route('user.signout') }}"><i class='fa fa-lock'></i> <span>Sign out</span></a></li>
    </ul><!-- /.sidebar-menu -->
    <center><img src="{{ asset('assets/dist/img/pln.jpg') }}" style="width: 50%; height: 50%; margin-top:200px;"></center>
  </section>
  <!-- /.sidebar -->
</aside>