app/Http/routes.php
		Route::get('lembagasertifikasi/{id}/delete', ['as' => 'dashboard.master.lembagasertifikasi.delete', 'uses' => 'MasterLembagasertifikasiController@destroy']);

		//////////////////////////////////////
		// ==============BIDANG=============//
		//////////////////////////////////////
		Route::resource('bidang', 'MasterBidangController', ['except' => ['destroy','show']]);
		Route::group(['prefix' => 'bidang'], function()
		{
			Route::get('{id}/delete', ['as' => 'dashboard.master.bidang.delete', 'uses' => 'MasterBidangController@destroy']);

			// =========================== sub bidang section ======================= //
			Route::get('{bidang_id}/subbidang', ['as' => 'dashboard.master.subbidang.bidang.index','uses' => 'MasterSubbidangController@showByBidang']);
			Route::get('{bidang_id}/subbidang/create', ['as' => 'dashboard.master.subbidang.bidang.create','uses' => 'MasterSubbidangController@create']);

			Route::group(['prefix' => 'subbidang'], function()
			{
				Route::get('create', ['as' => 'dashboard.master.subbidang.create','uses' => 'MasterSubbidangController@create']);
				Route::post('store', ['as' => 'dashboard.master.subbidang.store','uses' => 'MasterSubbidangController@store']);

				Route::get('{id}/edit', ['as' => 'dashboard.master.subbidang.edit','uses' => 'MasterSubbidangController@edit']);
				Route::put('{id}/update', ['as' => 'dashboard.master.subbidang.update','uses' => 'MasterSubbidangController@update']);
				Route::get('{id}/delete', ['as' => 'dashboard.master.subbidang.delete', 'uses' => 'MasterSubbidangController@destroy']);
			});
			
		});

		//////////////////////////////////////
		// =========UNIT KOMPETENSI=========//
		//////////////////////////////////////
		Route::resource('kompetensi', 'MasterKompetensiController', ['except' => ['destroy','show']]);

		Route::group(['prefix' => 'kompetensi'], function()
		{
			Route::get('{id}/delete', ['as' => 'dashboard.master.kompetensi.delete', 'uses' => 'MasterKompetensiController@destroy']);

			// ============================== Route master elemen kompetensi ================== //
			Route::resource('elemenkompetensi', 'MasterElemenkompetensiController', ['except' => ['destroy','show','index']]);
			
			Route::group(['prefix' => '{kompetensi_id}/elemenkompetensi'], function()
			{
				Route::get('/', ['as' => 'dashboard.master.elemenkompetensi.kompetensi.index','uses' => 'MasterElemenkompetensiController@showByKompetensi']);
				Route::get('create', ['as' => 'dashboard.master.elemenkompetensi.kompetensi.create','uses' => 'MasterElemenkompetensiController@create']);
			});
			
			Route::get('elemenkompetensi/{id}/delete', ['as' => 'dashboard.master.elemenkompetensi.delete', 'uses' => 'MasterElemenkompetensiController@destroy']);
		});

		//////////////////////////////////////
		// ===============UNIT==============//
		//////////////////////////////////////
		Route::group(['prefix'=>'unit'], function()
		{
			Route::get('/', ['as'=>'dashboard.master.unit.index', 'uses' => 'MasterUnitsController@index']);
			
			Route::resource('diklat', 'MasterUdiklatController', ['except' => 'show','destroy']);
			Route::get('diklat/{id}/delete', ['as' => 'dashboard.master.unit.diklat.delete', 'uses' => 'MasterUdiklatController@destroy']);
			Route::get('diklat/api/induk/{id}', ['dashboard.master.unit.diklat.api.induk', 'uses' => 'MasterUdiklatController@getUnitInduk']);
			
			Route::resource('induk', 'MasterUindukController', ['except' => 'show','destroy']);
			Route::get('induk/{id}/delete', ['as' => 'dashboard.master.unit.induk.delete', 'uses' => 'MasterUindukController@destroy']);
			Route::get('induk/api/cabang/{id}', ['dashboard.master.unit.induk.api.cabang', 'uses' => 'MasterUindukController@getUnitCabang']);

			Route::resource('cabang', 'MasterUcabangController', ['except' => 'show','destroy']);
			Route::get('cabang/{id}/delete', ['as' => 'dashboard.master.unit.cabang.delete', 'uses' => 'MasterUcabangController@destroy']);
			Route::get('cabang/api/ranting/{id}', ['dashboard.master.unit.cabang.api.ranting', 'uses' => 'MasterUcabangController@getUnitRanting']);

			Route::resource('ranting', 'MasterUrantingController', ['except' => 'show','destroy']);
			Route::get('ranting/{id}/delete', ['as' => 'dashboard.master.unit.ranting.delete', 'uses' => 'MasterUrantingController@destroy']);

			Route::resource('nonpln', 'MasterUnitnonplnController', ['except' => 'show','destroy']);
			Route::get('nonpln/{id}/delete', ['as' => 'dashboard.master.unit.nonpln.delete', 'uses' => 'MasterUnitnonplnController@destroy']);
		});

		//////////////////////////////////////
		// ==========JENJANG JABATAN========//
		//////////////////////////////////////
		Route::resource('jenjang', 'MasterJenjangController', ['except' => 'show','destroy']);
		Route::get('jenjang/{id}/delete', ['as' => 'dashboard.master.jenjang.delete', 'uses' => 'MasterJenjangController@destroy']);

		//////////////////////////////////////
		// ============PENDIDIKAN===========//
		//////////////////////////////////////
		Route::resource('pendidikan', 'MasterPendidikanController', ['except' => ['destroy','show']]);
		Route::get('pendidikan/{id}/delete', ['as' => 'dashboard.master.pendidikan.delete', 'uses' => 'MasterPendidikanController@destroy']);

		//////////////////////////////////////
		// ===========JENJANG GRADE=========//
		//////////////////////////////////////
		Route::resource('grade', 'MasterGradeController', ['except' => ['destroy','show']]);
		Route::get('grade/{id}/delete', ['as' => 'dashboard.master.grade.delete', 'uses' => 'MasterGradeController@destroy']);

		//////////////////////////////////////
		// ===============ROLE==============//
		//////////////////////////////////////
		Route::resource('userrole', 'UserRoleController', ['except' => ['destroy', 'show']]);
		Route::group(['prefix' => 'userrole'], function()
		{
			Route::get('{id}/delete', ['as' => 'dashboard.master.userrole.delete', 'uses' => 'UserRoleController@destroy']);
			Route::get('role/{role_id}/permission', ['as' => 'dashboard.master.userrole.role.permission', 'uses' => 'UserRoleController@setPermission']);
			Route::post('role/{role_id}/permission/update', ['as' => 'dashboard.master.userrole.role.permission.update', 'uses' => 'UserRoleController@updatePermission']);
		});

////////////////////////////////////////////////////////////////////////////////////////////////////////////////		
		
		// ================ Master Komponen biaya route section ========================== //
		Route::resource('komponenbiaya', 'MasterKomponenBiayaController', ['except' => ['destroy','show']]);
		Route::get('komponenbiaya/{id}/delete', ['as' => 'dashboard.master.komponenbiaya.delete', 'uses' => 'MasterKomponenBiayaController@destroy']);

		// ============================= Route master tim asesor ===================== //
		Route::resource('tim', 'MasterTimasesorController', ['except' => 'show','destroy']);
		Route::get('tim/{id}/delete', ['as' => 'dashboard.master.tim.delete', 'uses' => 'MasterTimasesorController@destroy']);

	});

/////////////////////////////////////////////////////////////////////////////////////////////
// ================================= REGISTRASI ROUTES =================================== //
/////////////////////////////////////////////////////////////////////////////////////////////
Route::get('registration', ['as' => 'dashboard.registration.index', 'uses' => 'Registration\RegistrationController@registrationDashboardIndex']);
Route::get('registration/{id}', ['as' => 'dashboard.registration.show', 'uses' => 'Registration\RegistrationController@registrationDashboardShow']);

/////////////////////////////////////////////////////////////////////////////////////////////
// ================================= PERMOHONAN ROUTES =================================== //
/////////////////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////
// ========PERMOHONAN SURAT=========//
//////////////////////////////////////
Route::resource('permohonan', 'PermohonanController', ['except' => 'delete']);
Route::group(['prefix' => 'permohonan'], function()
{
	Route::get('{id}/delete', ['as' => 'dashboard.permohonan.delete', 'uses' => 'PermohonanController@destroy']);

	// ========================= kompetensi permohonan route ========================== //
	Route::group(['prefix' => '{id}/kompetensi'], function()
	{
		Route::get('/', ['as' => 'dashboard.permohonan.kompetensi.index', 'uses' => 'PermohonanController@indexKompetensi']);
		Route::get('create', ['as' => 'dashboard.permohonan.kompetensi.create', 'uses' => 'PermohonanController@createKompetensi']);
		Route::post('store', ['as' => 'dashboard.permohonan.kompetensi.store', 'uses' => 'PermohonanController@storeKompetensi']);
		Route::get('{kompetensiid}/delete', ['as' => 'dashboard.permohonan.kompetensi.delete', 'uses' => 'PermohonanController@deleteKompetensi']);
	});

	// ========================= kompetensi peserta permohonan route =================== //
	Route::group(['prefix' => '{id}/kompetensi/{kompetensiid}/peserta'], function()
	{
		Route::get('/', ['as' => 'dashboard.permohonan.kompetensi.peserta.index', 'uses' => 'PermohonanController@indexKompetensiPeserta']);
		Route::get('create', ['as' => 'dashboard.permohonan.kompetensi.peserta.create', 'uses' => 'PermohonanController@createKompetensiPeserta']);
		Route::post('store', ['as' => 'dashboard.permohonan.kompetensi.peserta.store', 'uses' => 'PermohonanController@storeKompetensiPeserta']);
		Route::get('{pesertaid}/delete', ['as' => 'dashboard.permohonan.kompetensi.peserta.delete', 'uses' => 'PermohonanController@deleteKompetensiPeserta']);
	});
	
});

//////////////////////////////////////
// =========PERMOHONAN SDM==========//
//////////////////////////////////////
Route::resource('permohonansdm', 'PermohonanSdmController', ['except' => 'delete']);
Route::group(['prefix' => 'permohonansdm'], function()
{

app/Http/Controllers/MasterUindukController.php
<?php namespace Certification\Http\Controllers;

use Certification\Repositories\Unit\InterfaceUindukRepository;
use Certification\Repositories\Unit\InterfaceUdiklatRepository;
use Certification\Http\Requests\StoreMasterUnitindukRequest as RequestValidator;
use Certification\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Config, Flash;

class MasterUindukController extends Controller {

	/**
	 * [$uindukRepository description]
	 * 
	 * @var [type]
	 */
	private $uindukRepository;

	/**
	 * [$udiklatRepository description]
	 * 
	 * @var [type]
	 */
	private $udiklatRepository;
	
	/**
	 * [$title description]
	 * 
	 * @var [type]
	 */
	private $title;

	/**
	 * [__construct description]
	 * 
	 * @param InterfaceUindukRepository  $uindukRepository  [description]
	 * @param InterfaceUdiklatRepository $udiklatRepository [description]
	 * @return Void
	 */
	public function __construct(InterfaceUindukRepository $uindukRepository, InterfaceUdiklatRepository $udiklatRepository)
	{
		$this->uindukRepository = $uindukRepository;
		$this->udiklatRepository = $udiklatRepository;
		$this->title = 'Master Unit Induk';
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index(Request $request)
	{
		$data['title']             = $this->title;
		$data['subtitle']          = 'Daftar master unit induk';
		$data['unit']              = $this->uindukRepository->all('paginate');
		$data['pagination_number'] = numbering_pagination($request, Config::get('certification.default_pagination_count'));
		return view('backend.masteruinduk.index', compact('data'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$data['title']    = $this->title;
		$data['subtitle'] = 'Tambah master unit induk';
		$data['udiklat']  = $this->udiklatRepository->lists();
		return view('backend.masteruinduk.create', compact('data'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(RequestValidator $request)
	{
		$affected = $this->uindukRepository->store($request->except('_token'));
		if ($affected) {
			Flash::success('Data unit induk berhasil disimpan');
			return redirect()->route('dashboard.master.unit.induk.index');
		}
		Flash::error('Data unit induk gagal disimpan');
		return redirect()->back()->withInput();
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$data['title']    = $this->title;
		$data['subtitle'] = 'Edit master unit induk';
		$data['unit']	  = $this->uindukRepository->getById($id);
		$data['udiklat']  = $this->udiklatRepository->lists();
		return view('backend.masteruinduk.edit', compact('data'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(RequestValidator $request, $id)
	{
		$affected = $this->uindukRepository->update($id, $request->except('_token','_method'));
		if ($affected) {
			Flash::success('Data unit induk berhasil dirubah');
			return redirect()->route('dashboard.master.unit.induk.index');
		}
		Flash::error('Data unit induk gagal dirubah');
		return redirect()->back()->withInput();
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$this->uindukRepository->delete($id);
		Flash::success('Data unit induk berhasil dihapus');
		return redirect()->route('dashboard.master.unit.induk.index');
	}

	/**
	 * Get unit cabang data. Used for API purposes
	 * 
	 * @param  Integer $id unit induk id
	 * @return Json
	 */
	public function getUnitCabang($id)
	{
		return $this->uindukRepository->unitcabang($id);
	}

}

resources/views/backend/masteruinduk/create.blade.php
@extends('layouts.backend.master')
@section('content')
<div class="row">
	<div class="col-md-8">
		<div class="box box-primary">
			<div class="box-header with-border">
		     <h3>Form Tambah Unit Induk</h3>
		    </div><!-- /.box-header -->
		    <div class="box-body">
		    	@if (Session::has('flash_notification.message'))
				    <div class="alert alert-{{ Session::get('flash_notification.level') }}">
				        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				        {{ Session::get('flash_notification.message') }}
				    </div>
				@endif
		    	<form class="form-horizontal" action="{{ route('dashboard.master.unit.induk.store') }}" method="post">
		    		<input type="hidden" name="_token" value="{{ csrf_token() }}">
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">TUK</label>
                      <div class="col-sm-7">
                      	@if(isset($data['udiklat_single']))
                      		<input type="text" class="form-control" value="{{ $data['udiklat_single']->nama_udiklat }}" readonly="readonly">
                      		<input type="hidden" class="form-control" name="udiklat_id" value="{{ $data['udiklat_single']->id }}">
                      	@else
                      		{!! Form::select('udiklat_id', $data['udiklat'], null,['class'=>'selectpicker form-control','data-live-search'=>'true'])!!}
                      	@endif          
                      </div>
		    		</div>
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Nama Unit Induk</label>
                      <div class="col-sm-7">
                          <input type="text" class="form-control" placeholder="Nama unit induk" name="nama_unitinduk" required>
                      </div>
		    		</div>
		    </div>
		    <div class="box-footer">
		    	<div class="col-sm-4 col-md-offset-3">
    				<button type="submit" class="btn btn-primary">Simpan</button>&nbsp;
		            <a href="{{ route('dashboard.master.unit.induk.index') }}" class="btn btn-warning">Kembali</a>
    			</div>
		    </div>
		    </form>
		</div>
	</div>
</div>		    
@stop

resources/views/backend/masteruinduk/edit.blade.php
@extends('layouts.backend.master')
@section('content')
<div class="row">
	<div class="col-md-8">
		<div class="box box-primary">
			<div class="box-header with-border">
		     <h3>Form Edit Unit Induk</h3>
		    </div><!-- /.box-header -->
		    <div class="box-body">
		    	@if (Session::has('flash_notification.message'))
				    <div class="alert alert-{{ Session::get('flash_notification.level') }}">
				        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				        {{ Session::get('flash_notification.message') }}
				    </div>
				@endif
		    	{!! Form::open(['route' => ['dashboard.master.unit.induk.update', $data['unit']->id], 'class' => 'form-horizontal', 'method' => 'put']) !!}
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">TUK</label>
                      <div class="col-sm-7">
                  		{!! Form::select('udiklat_id', $data['udiklat'], $data['unit']->udiklat_id,['class'=>'selectpicker','data-live-search'=>'true'])!!}
                      </div>
		    		</div>
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Nama Unit Induk</label>
                      <div class="col-sm-7">
                          <input type="text" class="form-control" placeholder="Nama unit induk" name="nama_unitinduk" value="{{ $data['unit']->nama_unitinduk }}" required>
                      </div>
		    		</div>
		    </div>
		    <div class="box-footer">
		    	<div class="col-sm-4 col-md-offset-3">
    				<button type="submit" class="btn btn-primary">Update</button>&nbsp;
		            <a href="{{ route('dashboard.master.unit.induk.index') }}" class="btn btn-warning">Kembali</a>
    			</div>
		    </div>
		    {!! Form::close() !!}
		</div>
	</div>
</div>		    
@stop		    

resources/views/backend/masteruinduk/index.blade.php
@extends('layouts.backend.master')
@section('content')
<div class="row">
	<div class="col-md-10">
		<div class="box box-primary">
		@if(Auth::user()->can('can_write_masterunit'))
			<div class="box-header with-border">
		      <a href="{{ route('dashboard.master.unit.induk.create') }}" class="btn btn-sm btn-success"><i class="fa fa-plus"></i> Tambah Unit Induk</a>&nbsp;
		    </div><!-- /.box-header -->
		@endif
		    <div class="box-body">
		    @if (Session::has('flash_notification.message'))
			    <div class="alert alert-{{ Session::get('flash_notification.level') }}">
			        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			        {{ Session::get('flash_notification.message') }}
			    </div>
			@endif
		    	 <div class="table-responsive">
			        <table class="table no-margin table-condensed table-bordered table-hover">
			          <thead class="bg-info">
				          <tr>
				          	<th class="col-md-1">No.</th>
				          	<th class="col-md-2">Nama TUK</th>
				          	<th class="col-md-2">Nama Unit Induk</th>
				          	<th class="col-md-2">Jumlah Unit Cabang</th>
				          	<th class="col-md-2 text-center">Aksi</th>
				          </tr>
			          </thead>
			          <tbody>
			          @forelse($data['unit'] as $uinduk)
				          <tr>
				          	<td>{{ $data['pagination_number'] }}</td>
				          	<td>{{ $uinduk->udiklat->nama_udiklat }}</td>
				          	<td>{{ $uinduk->nama_unitinduk }}</td>
				          	<td>{{ $uinduk->unitcabang->count() }} Unit</td>
				          	<td class="text-center">
				          	@if(Auth::user()->can('can_write_masterunit'))
				          		<a href="{{ route('dashboard.master.unit.induk.edit', ['id'=>$uinduk->id]) }}" class="btn btn-sm btn-warning"><i class="fa fa-edit"></i> Edit</a>
				          		<a href="{{ route('dashboard.master.unit.induk.delete', ['id'=>$uinduk->id]) }}" class="btn btn-sm btn-danger" onclick="return confirm('Hapus data?'); "><i class="fa fa-trash"></i> Delete</a>
				          	@else
				          		-
				          	@endif
				          	</td>
				          </tr>
				      <?php $data['pagination_number']++; ?>    
			          @empty
			          	<tr>
			          		<td colspan="4" class="text-center">Tidak ada data</td>
			          	</tr>
			          @endforelse
			          </tbody>
			        </table><br>
			        <div class="text-center">
			        	{!! paginationHelper($data['unit']->render()) !!}
			        </div>
			    </div>      
		    </div>
		</div>
	</div>
</div>
@stop