app/Http/routes.php
				Route::get('{kelompok_id}/delete', ['as' => 'dashboard.master.asesor.kelompok.delete','uses' => 'MasterAsesorController@deleteKelompok']);
				Route::get('create', ['as' => 'dashboard.master.asesor.kelompok.create','uses' => 'MasterAsesorController@createKelompok']);
				Route::post('store', ['as' => 'dashboard.master.asesor.kelompok.store','uses' => 'MasterAsesorController@storeKelompok']);
			});
			
			Route::get('{id}/testhistory', ['as' => 'dashboard.master.asesor.testhistory.index','uses' => 'MasterAsesorController@indexTest']);

			Route::resource('kompetensiasesor', 'MasterKompetensiasesorController', ['only' => ['create','store']]);
			Route::group(['prefix' => 'kompetensiasesor'], function()
			{	
				Route::get('{asesor_id}', ['as' => 'dashboard.master.kompetensiasesor.asesor.index','uses' => 'MasterKompetensiasesorController@showByAsesor']);
				Route::get('{asesor_id}/create', ['as' => 'dashboard.master.kompetensiasesor.asesor.create','uses' => 'MasterKompetensiasesorController@create']);
				Route::get('detach/{asesor}/{kompetensi}', ['as' => 'dashboard.master.asesor.kompetensiasesor.delete', 'uses' => 'MasterKompetensiasesorController@destroy']);
			});

			// ======================= Route sub bidang asesor ============================ //
			Route::group(['prefix' => '{id}/subbidang'], function()
			{
				Route::get('/', ['as' => 'dashboard.master.asesor.subbidang.index', 'uses' => 'MasterAsesorController@indexSubbidang']);
				Route::get('create', ['as' => 'dashboard.master.asesor.subbidang.create', 'uses' => 'MasterAsesorController@createSubbidang']);
				Route::post('store', ['as' => 'dashboard.master.asesor.subbidang.store', 'uses' => 'MasterAsesorController@storeSubbidang']);
				Route::get('{subbidangId}/delete', ['as' => 'dashboard.master.asesor.subbidang.delete', 'uses' => 'MasterAsesorController@deleteSubbidang']);
			});

			// ========================= Route master Sertifikat Asesor ===================== //
			Route::get('{asesor_id}/sertifikatasesor', ['as' => 'dashboard.master.sertifikatasesor.asesor.index','uses' => 'MasterSertifikatAsesorController@showByAsesor']);
			Route::get('{asesor_id}/sertifikatasesor/create', ['as' => 'dashboard.master.sertifikatasesor.asesor.create','uses' => 'MasterSertifikatAsesorController@create']);
			
			Route::resource('sertifikatasesor', 'MasterSertifikatAsesorController', ['except' => ['destroy','show','index']]);

			Route::group(['prefix' => 'sertifikatasesor'], function()
			{
				Route::get('{id}/delete/{asesor}', ['as' => 'dashboard.master.sertifikatasesor.delete', 'uses' => 'MasterSertifikatAsesorController@destroy']);
				Route::get('{id}/edit', ['as' => 'dashboard.master.sertifikatasesor.edit','uses' => 'MasterSertifikatAsesorController@edit']);
				Route::put('{id}/update/{asesor}', ['as' => 'dashboard.master.sertifikatasesor.update','uses' => 'MasterSertifikatAsesorController@update']);
			});
	
		});

		//////////////////////////////////////
		// ============AKREDITOR============//
		//////////////////////////////////////
		Route::resource('akreditor', 'MasterLembagaController', ['except' => ['destroy','show']]);
		Route::get('akreditor/{id}/delete', ['as' => 'dashboard.master.akreditor.delete', 'uses' => 'MasterLembagaController@destroy']);

		//////////////////////////////////////
		// =======LEMBAGA SERTIFIKASI=======//
		//////////////////////////////////////
		Route::resource('lembagasertifikasi', 'MasterLembagasertifikasiController', ['except' => ['destroy','show']]);
		Route::get('lembagasertifikasi/{id}/delete', ['as' => 'dashboard.master.lembagasertifikasi.delete', 'uses' => 'MasterLembagasertifikasiController@destroy']);

		//////////////////////////////////////
		// ==============BIDANG=============//
		//////////////////////////////////////
		Route::resource('bidang', 'MasterBidangController', ['except' => ['destroy','show']]);
		Route::group(['prefix' => 'bidang'], function()
		{
			Route::get('{id}/delete', ['as' => 'dashboard.master.bidang.delete', 'uses' => 'MasterBidangController@destroy']);

			// =========================== sub bidang section ======================= //
			Route::get('{bidang_id}/subbidang', ['as' => 'dashboard.master.subbidang.bidang.index','uses' => 'MasterSubbidangController@showByBidang']);
			Route::get('{bidang_id}/subbidang/create', ['as' => 'dashboard.master.subbidang.bidang.create','uses' => 'MasterSubbidangController@create']);

			Route::group(['prefix' => 'subbidang'], function()
			{
				Route::get('create', ['as' => 'dashboard.master.subbidang.create','uses' => 'MasterSubbidangController@create']);
				Route::post('store', ['as' => 'dashboard.master.subbidang.store','uses' => 'MasterSubbidangController@store']);

				Route::get('{id}/edit', ['as' => 'dashboard.master.subbidang.edit','uses' => 'MasterSubbidangController@edit']);
				Route::put('{id}/update', ['as' => 'dashboard.master.subbidang.update','uses' => 'MasterSubbidangController@update']);
				Route::get('{id}/delete', ['as' => 'dashboard.master.subbidang.delete', 'uses' => 'MasterSubbidangController@destroy']);
			});
			
		});

		//////////////////////////////////////
		// =========UNIT KOMPETENSI=========//
		//////////////////////////////////////
		Route::resource('kompetensi', 'MasterKompetensiController', ['except' => ['destroy','show']]);

		Route::group(['prefix' => 'kompetensi'], function()
		{
			Route::get('{id}/delete', ['as' => 'dashboard.master.kompetensi.delete', 'uses' => 'MasterKompetensiController@destroy']);

			// ============================== Route master elemen kompetensi ================== //
			Route::resource('elemenkompetensi', 'MasterElemenkompetensiController', ['except' => ['destroy','show','index']]);
			
			Route::group(['prefix' => '{kompetensi_id}/elemenkompetensi'], function()
			{
				Route::get('/', ['as' => 'dashboard.master.elemenkompetensi.kompetensi.index','uses' => 'MasterElemenkompetensiController@showByKompetensi']);
				Route::get('create', ['as' => 'dashboard.master.elemenkompetensi.kompetensi.create','uses' => 'MasterElemenkompetensiController@create']);
			});
			
			Route::get('elemenkompetensi/{id}/delete', ['as' => 'dashboard.master.elemenkompetensi.delete', 'uses' => 'MasterElemenkompetensiController@destroy']);
		});

		//////////////////////////////////////
		// ===============UNIT==============//
		//////////////////////////////////////
		Route::group(['prefix'=>'unit'], function()
		{
			Route::get('/', ['as'=>'dashboard.master.unit.index', 'uses' => 'MasterUnitsController@index']);
			
			Route::resource('diklat', 'MasterUdiklatController', ['except' => 'show','destroy']);
			Route::get('diklat/{id}/delete', ['as' => 'dashboard.master.unit.diklat.delete', 'uses' => 'MasterUdiklatController@destroy']);
			Route::get('diklat/api/induk/{id}', ['dashboard.master.unit.diklat.api.induk', 'uses' => 'MasterUdiklatController@getUnitInduk']);
			
			Route::resource('induk', 'MasterUindukController', ['except' => 'show','destroy']);
			Route::get('induk/{id}/delete', ['as' => 'dashboard.master.unit.induk.delete', 'uses' => 'MasterUindukController@destroy']);
			Route::get('induk/api/cabang/{id}', ['dashboard.master.unit.induk.api.cabang', 'uses' => 'MasterUindukController@getUnitCabang']);

			Route::resource('cabang', 'MasterUcabangController', ['except' => 'show','destroy']);
			Route::get('cabang/{id}/delete', ['as' => 'dashboard.master.unit.cabang.delete', 'uses' => 'MasterUcabangController@destroy']);
			Route::get('cabang/api/ranting/{id}', ['dashboard.master.unit.cabang.api.ranting', 'uses' => 'MasterUcabangController@getUnitRanting']);

			Route::resource('ranting', 'MasterUrantingController', ['except' => 'show','destroy']);
			Route::get('ranting/{id}/delete', ['as' => 'dashboard.master.unit.ranting.delete', 'uses' => 'MasterUrantingController@destroy']);

			Route::resource('nonpln', 'MasterUnitnonplnController', ['except' => 'show','destroy']);
			Route::get('nonpln/{id}/delete', ['as' => 'dashboard.master.unit.nonpln.delete', 'uses' => 'MasterUnitnonplnController@destroy']);
		});

		//////////////////////////////////////
		// ==========JENJANG JABATAN========//
		//////////////////////////////////////
		Route::resource('jenjang', 'MasterJenjangController', ['except' => 'show','destroy']);
		Route::get('jenjang/{id}/delete', ['as' => 'dashboard.master.jenjang.delete', 'uses' => 'MasterJenjangController@destroy']);

		//////////////////////////////////////
		// ============PENDIDIKAN===========//
		//////////////////////////////////////
		Route::resource('pendidikan', 'MasterPendidikanController', ['except' => ['destroy','show']]);
		Route::get('pendidikan/{id}/delete', ['as' => 'dashboard.master.pendidikan.delete', 'uses' => 'MasterPendidikanController@destroy']);

		//////////////////////////////////////
		// ===========JENJANG GRADE=========//
		//////////////////////////////////////
		Route::resource('grade', 'MasterGradeController', ['except' => ['destroy','show']]);
		Route::get('grade/{id}/delete', ['as' => 'dashboard.master.grade.delete', 'uses' => 'MasterGradeController@destroy']);

		//////////////////////////////////////
		// ===============ROLE==============//
		//////////////////////////////////////
		Route::resource('userrole', 'UserRoleController', ['except' => ['destroy', 'show']]);
		Route::group(['prefix' => 'userrole'], function()
		{
			Route::get('{id}/delete', ['as' => 'dashboard.master.userrole.delete', 'uses' => 'UserRoleController@destroy']);
			Route::get('role/{role_id}/permission', ['as' => 'dashboard.master.userrole.role.permission', 'uses' => 'UserRoleController@setPermission']);
			Route::post('role/{role_id}/permission/update', ['as' => 'dashboard.master.userrole.role.permission.update', 'uses' => 'UserRoleController@updatePermission']);
		});

////////////////////////////////////////////////////////////////////////////////////////////////////////////////		
		

app/Http/Controllers/MasterLembagasertifikasiController.php
<?php namespace Certification\Http\Controllers;

use Certification\Http\Requests\StoreMasterLembagasertifikasiRequest as RequestValidator;
use Certification\Repositories\LembagaSertifikasi\InterfaceLembagaSertifikasiRepository;
use Certification\Http\Controllers\Controller;
use Illuminate\Http\Request as Request;
use Config, Flash;

class MasterLembagasertifikasiController extends Controller {

	/**
	 * Lembaga sertifikasi repository
	 * 
	 * @var Interface
	 */
	private $lembagasertifikasiRepository;
	
	/**
	 * Modul title
	 * 
	 * @var String
	 */
	private $title;

	/**
	 * Class instance
	 * 
	 * @param InterfaceLembagaSertifikasiRepository $lembagasertifikasiRepository
	 */
	public function __construct(InterfaceLembagaSertifikasiRepository $lembagasertifikasiRepository)
	{
		$this->lembagasertifikasiRepository = $lembagasertifikasiRepository;
		$this->title                        = 'Manajemen Master Lembaga Sertifikasi';
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index(Request $request)
	{
		$data['title']              = $this->title;
		$data['subtitle']           = 'Daftar master lembaga sertifikasi';
		$data['lembagasertifikasi'] = $this->lembagasertifikasiRepository->all(true);
		$data['pagination_number']  = numbering_pagination($request, Config::get('certification.default_pagination_count'));
		return view('backend.masterlembagasertifikasi.index', compact('data'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$data['title']    = $this->title;
		$data['subtitle'] = 'Tambah master lembaga sertifikasi';
		return view('backend.masterlembagasertifikasi.create', compact('data'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(RequestValidator $request)
	{
		$affected = $this->lembagasertifikasiRepository->store($request->except('_token'));
		if($affected) {
			Flash::success('Data lembaga sertifikasi berhasil disimpan');
			return redirect()->route('dashboard.master.lembagasertifikasi.index');
		}
		Flash::error('Data lembaga sertifikasi gagal disimpan');
		return redirect()->back();
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$data['title']              = $this->title;
		$data['subtitle']           = 'Edit master lembaga sertifikasi';
		$data['lembagasertifikasi'] = $this->lembagasertifikasiRepository->getById($id);
		return view('backend.masterlembagasertifikasi.edit', compact('data'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, RequestValidator $request)
	{
		$affected = $this->lembagasertifikasiRepository->update($id, $request->except('_token','_method'));
		if($affected) {
			Flash::success('Data lembaga sertifikasi berhasil dirubah');
			return redirect()->route('dashboard.master.lembagasertifikasi.index');
		}
		Flash::error('Data lembaga sertifikasi gagal disimpan');
		return redirect()->back();
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$this->lembagasertifikasiRepository->delete($id);
		Flash::success('Data lembaga sertifikasi berhasil dihapus');
		return redirect()->route('dashboard.master.lembagasertifikasi.index');
	}	
}

resources/views/backend/masterlembagasertifikasi/create.blade.php
@extends('layouts.backend.master')
@section('content')
<div class="row">
	<div class="col-md-8">
		<div class="box box-primary">
			<div class="box-header with-border">
		     <h3>Form Tambah Lembaga Sertifikasi</h3>
		    </div><!-- /.box-header -->
		    <div class="box-body">
		    	@if($errors->any())
		    		<div class="alert alert-danger alert-dismissable">
		    			<ul>
			    		<button class="close" aria-hidden="true" data-dismiss="alert" type="button">x</button>
			    		@foreach($errors->all() as $error)
			    			<li>{{ $error }}</li>
			    		@endforeach
			    		</ul>
			    	</div>
		    	@endif
		    	@if (Session::has('flash_notification.message'))
				    <div class="alert alert-{{ Session::get('flash_notification.level') }}">
				        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				        {{ Session::get('flash_notification.message') }}
				    </div>
				@endif
		    	<form class="form-horizontal" action="{{ route('dashboard.master.lembagasertifikasi.store') }}" method="post">
		    		<input type="hidden" name="_token" value="{{ csrf_token() }}">
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Nama Lembaga</label>
                      <div class="col-sm-7">
                          <input type="text" class="form-control" placeholder="Nama Lembaga Sertifikasi" name="nama_lembagasertifikasi" required>
                      </div>
		    		</div>
					<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Kode Registrasi</label>
                      <div class="col-sm-7">
                          <input type="text" class="form-control" placeholder="Kode registrasi lsp" name="koderegistrasilsp">
                      </div>
		    		</div>
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Grup</label>
                      <div class="col-sm-4">
                          {!! Form::select('grup', ['pln' => 'PLN', 'kerjasama' => 'Kerjasama'], 'null', ['class' => 'form-control']) !!}
                      </div>
		    		</div>
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Sertifikat</label>
                      <div class="col-sm-4">
                          {!! Form::select('jenis_sertifikat', ['pln' => 'PLN', 'bnsp' => 'BNSP'], 'null', ['class' => 'form-control']) !!}
                      </div>
		    		</div>		    		
		    </div>
		    <div class="box-footer">
		    	<div class="col-sm-4 col-md-offset-3">
    				<button type="submit" class="btn btn-primary">Simpan</button>&nbsp;
		            <a href="{{ route('dashboard.master.lembagasertifikasi.index') }}" class="btn btn-warning">Kembali</a>
    			</div>
		    </div>
		    </form>
		</div>
	</div>
</div>		    
@stop		    

resources/views/backend/masterlembagasertifikasi/edit.blade.php
@extends('layouts.backend.master')
@section('content')
<div class="row">
	<div class="col-md-8">
		<div class="box box-primary">
			<div class="box-header with-border">
		     <h3>Edit Lembaga Sertifikasi</h3>
		    </div><!-- /.box-header -->
		    <div class="box-body">
		    	@if($errors->any())
		    		<div class="alert alert-danger alert-dismissable">
		    			<ul>
			    		<button class="close" aria-hidden="true" data-dismiss="alert" type="button">x</button>
			    		@foreach($errors->all() as $error)
			    			<li>{{ $error }}</li>
			    		@endforeach
			    		</ul>
			    	</div>
		    	@endif
		    	@if (Session::has('flash_notification.message'))
				    <div class="alert alert-{{ Session::get('flash_notification.level') }}">
				        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				        {{ Session::get('flash_notification.message') }}
				    </div>
				@endif
		    	<form class="form-horizontal" action="{{ route('dashboard.master.lembagasertifikasi.update', ['id'=>$data['lembagasertifikasi']->id ]) }}" method="post">
		    		<input type="hidden" name="_token" value="{{ csrf_token() }}">
		    		<input type="hidden" name="_method" value="put">
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Nama Lembaga</label>
                      <div class="col-sm-7">
                          <input type="text" class="form-control" placeholder="Nama Lembaga Sertifikasi" name="nama_lembagasertifikasi" value="{{ $data['lembagasertifikasi']->nama_lembagasertifikasi }}" required>
                      </div>
		    		</div>
					<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Kode Registrasi</label>
                      <div class="col-sm-7">
                          <input type="text" class="form-control" placeholder="Kode registrasi lsp" name="koderegistrasilsp" value="{{ $data['lembagasertifikasi']->koderegistrasilsp }}">
                      </div>
		    		</div>	
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Grup</label>
                      <div class="col-sm-4">
                          {!! Form::select('grup', ['pln' => 'PLN', 'kerjasama' => 'Kerjasama'], $data['lembagasertifikasi']->grup, ['class' => 'form-control']) !!}
                      </div>
		    		</div>
		    		<div class="form-group">
                      <label for="nama" class="col-sm-3 control-label">Sertifikat</label>
                      <div class="col-sm-4">
                          {!! Form::select('jenis_sertifikat', ['pln' => 'PLN', 'bnsp' => 'BNSP'], $data['lembagasertifikasi']->jenis_sertifikat, ['class' => 'form-control']) !!}
                      </div>
		    		</div>	    		
		    </div>
		    <div class="box-footer">
		    	<div class="col-sm-4 col-md-offset-3">
    				<button type="submit" class="btn btn-primary">Update</button>&nbsp;
		            <a href="{{ route('dashboard.master.lembagasertifikasi.index') }}" class="btn btn-warning">Kembali</a>
    			</div>
		    </div>
		    </form>
		</div>
	</div>
</div>		    
@stop		    

resources/views/backend/masterlembagasertifikasi/index.blade.php
@extends('layouts.backend.master')
@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="box box-primary">
		@if(Auth::user()->can('can_write_masterlembagasertifikasi'))
			<div class="box-header with-border">
		      <a href="{{ route('dashboard.master.lembagasertifikasi.create') }}" class="btn btn-sm btn-success"><i class="fa fa-plus"></i> Tambah Lembaga Sertifikasi</a>
		    </div><!-- /.box-header -->
		@endif
		    <div class="box-body">
		    @if (Session::has('flash_notification.message'))
			    <div class="alert alert-{{ Session::get('flash_notification.level') }}">
			        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			        {{ Session::get('flash_notification.message') }}
			    </div>
			@endif
		    	 <div class="table-responsive">
			        <table class="table no-margin table-condensed table-bordered table-hover">
			          <thead class="bg-info">
				          <tr>
				          	<th>No.</th>
				          	<th class="col-md-3">Nama Lembaga Sertifikasi</th>
				          	<th class="col-md-2">Kode Registrasi</th>
				          	<th>Grup</th>
				          	<th>Sertifikat</th>
				          	<th class="col-md-2">Jumlah Asesor</th>
				          	<th class="col-md-2">Jumlah Administrator</th>
				          	<th class="col-md-3 text-center">Aksi</th>
				          </tr>
			          </thead>
			          <tbody>
			          @forelse($data['lembagasertifikasi'] as $lembaga)
				          <tr>
				          	<td>{{ $data['pagination_number'] }}</td>
				          	<td>{{ $lembaga->nama_lembagasertifikasi }}</td>
				          	<td>{{ (! is_null($lembaga->koderegistrasilsp) ? $lembaga->koderegistrasilsp : '-')}}</td>
				          	<td>{{ $lembaga->grup }}</td>
				          	<td>{{ $lembaga->jenis_sertifikat }}</td>
				          	<td>{{ $lembaga->asesor->count() }} Asesor</td>
				          	<td>{{ $lembaga->administrator->count() }} Administrator</td>
				          	<td class="text-center">
				          	@if(Auth::user()->can('can_write_masterlembagasertifikasi'))
				          		<a href="{{ route('dashboard.master.lembagasertifikasi.edit', ['id' => $lembaga->id]) }}" class="btn btn-sm btn-warning"><i class="fa fa-edit"></i> Edit</a>
				          		<a href="{{ route('dashboard.master.lembagasertifikasi.delete', ['id' => $lembaga->id]) }}" class="btn btn-sm btn-danger" onclick="return confirm('Hapus data?'); "><i class="fa fa-trash"></i> Delete</a>
				          	@else
				          		-
				          	@endif
				          	</td>
				          </tr>
				      <?php $data['pagination_number']++; ?>
				      @empty
				      <tr>
				      	<td colspan="4" class="text-center">Tidak ada data</td>
				      </tr>    
			          @endforelse
			          </tbody>
			        </table><br>
			        <div class="text-center">
			        	{!! paginationHelper($data['lembagasertifikasi']->render()) !!}
			        </div>
			    </div>      
		    </div>
		</div>
	</div>
</div>
@stop